# ========================================
# Bisheng Enterprise - Alertmanager Configuration
# ========================================
# Alert routing and notifications
# ========================================

global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertmanager@bisheng.local'
  smtp_require_tls: false

# ==================== Templates ====================
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# ==================== Route Configuration ====================
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  
  routes:
    # Critical alerts
    - match:
        severity: critical
      receiver: 'critical'
      continue: true
    
    # Warning alerts
    - match:
        severity: warning
      receiver: 'warning'
    
    # Database alerts
    - match:
        category: database
      receiver: 'database-team'
    
    # Application alerts
    - match:
        category: application
      receiver: 'dev-team'

# ==================== Receivers ====================
receivers:
  
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 'admin@bisheng.local'
        headers:
          Subject: '[Bisheng] Alert: {{ .GroupLabels.alertname }}'
        html: |
          <h2>Alert: {{ .GroupLabels.alertname }}</h2>
          <p><strong>Severity:</strong> {{ .CommonLabels.severity }}</p>
          <p><strong>Summary:</strong> {{ .CommonAnnotations.summary }}</p>
          <p><strong>Description:</strong> {{ .CommonAnnotations.description }}</p>

  # Critical alerts
  - name: 'critical'
    email_configs:
      - to: 'critical@bisheng.local'
        headers:
          Subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'
        send_resolved: true

  # Warning alerts
  - name: 'warning'
    email_configs:
      - to: 'warnings@bisheng.local'
        headers:
          Subject: '⚠️  [WARNING] {{ .GroupLabels.alertname }}'
        send_resolved: true

  # Database team
  - name: 'database-team'
    email_configs:
      - to: 'dba@bisheng.local'
        headers:
          Subject: '[DB] {{ .GroupLabels.alertname }}'

  # Development team
  - name: 'dev-team'
    email_configs:
      - to: 'dev@bisheng.local'
        headers:
          Subject: '[DEV] {{ .GroupLabels.alertname }}'

# ==================== Inhibition Rules ====================
inhibit_rules:
  # Inhibit warning if critical is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit any alert if service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

# EOF
