# ========================================
# Bisheng Enterprise - Grafana Datasources
# ========================================
# Auto-provisioned data sources
# ========================================

apiVersion: 1

datasources:
  # ==================== Prometheus ====================
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      queryTimeout: 60s
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
      cacheLevel: High
      incrementalQuerying: true
      incrementalQueryOverlapWindow: 10m
      disableRecordingRules: false
    version: 1

  # ==================== PostgreSQL ====================
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: bisheng_dev
    user: bisheng
    secureJsonData:
      password: 'dev_postgres_pass_123'
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    editable: true
    version: 1

  # ==================== Redis (via Prometheus) ====================
  - name: Redis
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
    version: 1

  # ==================== Loki (Optional - for logs) ====================
  # Uncomment when Loki is added
  # - name: Loki
  #   type: loki
  #   access: proxy
  #   url: http://loki:3100
  #   editable: true
  #   jsonData:
  #     maxLines: 1000
  #   version: 1

# EOF
