# ============================================
# Elasticsearch Configuration
# Bisheng Enterprise
# ============================================

cluster.name: bisheng-cluster
node.name: bisheng-es-node-1

# Network
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Discovery (single node)
discovery.type: single-node

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
path.repo: /backups

# Memory
bootstrap.memory_lock: true

# Security
xpack.security.enabled: true
xpack.security.enrollment.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# Monitoring
xpack.monitoring.collection.enabled: true

# License
xpack.license.self_generated.type: basic

# Index settings
action.auto_create_index: true
action.destructive_requires_name: true

# Performance
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 20%

# Thread pools
thread_pool.write.queue_size: 1000
thread_pool.search.queue_size: 1000

# Circuit breakers
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Recovery
indices.recovery.max_bytes_per_sec: 100mb

# Slow logs
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.fetch.warn: 1s
index.indexing.slowlog.threshold.index.warn: 10s