database:
  driver: postgresql
  host: postgres
  port: 5432
  name: bisheng_dev
  user: bisheng_dev
  password: StrongPass1234_5678_ABCDEFGH

redis:
  host: redis
  port: 6379
  password: RedisStrongPass1234_5678_ijkl

vector_db:
  type: milvus
  host: milvus
  port: 19530

search_engine:
  type: elasticsearch
  host: elasticsearch
  port: 9200
  username: elastic
  password: ElasticStrongPass1234_5678_MNO

storage:
  type: minio
  endpoint: minio:9000
  access_key: bisheng_admin
  secret_key: MinioSecurePass9876_5432_XYZ
  bucket: bisheng-production

llm:
  openai:
    api_key: ${OPENAI_API_KEY}
    model: gpt-4-turbo
  anthropic:
    api_key: ${ANTHROPIC_API_KEY}
    model: claude-3-opus
  google:
    api_key: ${GOOGLE_API_KEY}
    model: gemini-1.5-pro
  embedding_model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

security:
  jwt_secret: ${JWT_SECRET}
  cors_origins: ["https://bisheng.ai", "http://localhost:80"]

features:
  office_processing: true
  fine_tuning: true
  multi_language: ["ar", "zh"]